"""
Constants variable used for the app
"""
CATEGORY_TO_TEXT = {
    "zh-tw": {
        "APPL": "應用",
        "PRAC": "最佳實踐與慣例",
        "COM": "社群",
        "DB": "資料庫",
        "DATA": "資料分析",
        "EDU": "教育",
        "EMBED": "嵌入式系統",
        "FIN": "金融科技",
        "IOT": "物聯網",
        "GAME": "遊戲",
        "GRAPH": "圖像處理",
        "ML": "機器學習",
        "NLP": "自然語言處理",
        "CORE": "Python 核心",
        "TOOL": "專案建置工具",
        "SCI": "科學",
        "SEC": "資訊安全",
        "ADMIN": "系統管理",
        "TEST": "測試",
        "WEB": "網站框架",
        "OTHER": "其他",
    },
    "en-us": {
        "APPL": "Application",
        "PRAC": "Best Practices & Patterns",
        "COM": "Community",
        "DB": "Databases",
        "DATA": "Data Analysis",
        "EDU": "Education",
        "EMBED": "Embedded Systems",
        "FIN": "FinTech",
        "IOT": "Internet of Things",
        "GAME": "Gaming",
        "GRAPH": "Graphics",
        "ML": "Machine Learning",
        "NLP": "Natural Language Processing",
        "CORE": "Python Core",
        "TOOL": "Project Tooling",
        "SCI": "Science",
        "SEC": "Security",
        "ADMIN": "Systems Administration",
        "TEST": "Testing",
        "WEB": "Web Frameworks",
        "OTHER": "Other",
    },
}
LANGUAGE_TO_TEXT = {
    "zh-tw": {
        "ENEN": "英文演講",
        "ZHEN": "中文演講/英文投影片",
        "ZHZH": "中文演講/中文投影片",
        "TAI": "臺灣閩南語",
        "JPEN": "日語",
    },
    "en-us": {
        "ENEN": "English talk",
        "ZHEN": "Chinese talk w. English slides",
        "ZHZH": "Chinese talk w. Chinese slides",
        "TAI": "Taiwanese Hokkien",
        "JPEN": "Japanese talk",
    },
}
PYTHON_LEVEL_TO_TEXT = {
    "EXPERIENCED": "●●●",
    "INTERMEDIATE": "●●○",
    "NOVICE": "●○○",
}
